name: yacht_booking
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  get: ^4.6.5
  shared_preferences: ^2.0.15
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^10.1.0
  pin_code_fields: ^7.4.0
  dio: ^4.0.6
  skeleton_text: ^3.0.0
  cached_network_image: ^3.2.1
  flutter_screenutil: ^5.5.3+2
  fluttertoast: ^8.0.9
  flutter_slidable: ^2.0.0
  multi_image_picker_view: ^0.0.6
  flutter_image_compress: ^1.1.1
  image_picker: ^0.8.5+3
  image_cropper: ^3.0.0
  carousel_slider: ^4.1.1
  flutter_switch: ^0.3.2
  google_maps_flutter: ^2.1.12
  geocoding: ^2.0.5
  geolocator: ^9.0.1
  intl: ^0.17.0
  country_pickers: ^2.0.0
  syncfusion_flutter_sliders: ^20.2.46
  percent_indicator: ^4.2.2
  flutter_launcher_icons: ^0.10.0
  flutter_svprogresshud: ^1.0.0
  lazy_load_scrollview: ^1.3.0
  modal_bottom_sheet: ^2.1.0
  multi_select_flutter: ^4.1.2
  firebase_core: ^1.21.1
  cloud_firestore: ^3.4.6
  firebase_messaging: ^13.0.0
  flutter_local_notifications: ^9.9.0
  firebase_storage: ^10.3.7
  flutter_rating_bar: ^4.0.1
  # permission_handler: ^10.0.0
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/app_icon.png"


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/main_icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Cairo
       fonts:
         - asset: assets/fonts/Cairo-Regular.ttf
           weight: 500
         - asset: assets/fonts/Cairo-Bold.ttf
     - family: FlatRegular
       fonts:
         - asset: assets/fonts/Jf-Flat-Regular.ttf
