name: salon_provider
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^2.3.1
  pin_code_text_field: ^1.8.0
  flutter_screenutil: ^5.5.3+1
  intl_phone_field: ^3.0.1
  font_awesome_flutter: ^8.11.0
  modal_bottom_sheet: ^1.0.0
  # table_calendar: ^2.3.3
  rating_bar: ^0.2.0
  flutter_image_compress: ^1.1.0
  flutter_spinkit: ^4.1.2
  get: ^3.26.0
  dio: ^4.0.4
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.9
  url_launcher: ^6.0.20
  flutter_svg: ^1.0.3
  cached_network_image: ^2.5.0
  geolocator: ^8.2.0
  google_maps_flutter: ^2.1.2
  firebase_messaging: ^11.2.10
  firebase_core: ^1.13.1
  string_validator: ^0.1.4
  date_time_picker: ^2.1.0
  skeleton_text: ^3.0.0
  image_cropper: ^2.0.3
  image_picker: ^0.8.5+3
  simple_fontellico_progress_dialog: ^0.2.1
  path_provider: ^2.0.10
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/gif/
    - assets/svg/
    - assets/fonts/
    - assets/animations/